<?php

namespace AppBundle\Repository;

/**
 * AdvertRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdvertRepository extends \Doctrine\ORM\EntityRepository
{
    public function showActiveAdverts() {
        $manager = $this->getEntityManager();
        
        $query = $manager->createQuery("SELECT advert FROM AppBundle:Advert advert WHERE advert.expireDate > CURRENT_TIMESTAMP()");
        return $query->getResult();
    }
 
}
